name: Test Docker on GitHub Actions

on:
  push:
    branches: 
      - test

jobs:
  push_container:
    runs-on: arc-runner-set
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    container:
      image: docker:cli
    steps:
      - name: Run Docker
        run: |
          docker run hello-world

      - name: Test Docker
        run: |
          docker version
          docker info
